# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependency
        run: yarn install
      - name: Clear Running Process
        run: echo "console.log('hello')" >> temp.js; pm2 start temp.js; pm2 delete all; # stop all started process
      - name: Clear Running Process
        run: echo "console.log('hello')" >> temp.js; pm2 start temp.js; pm2 delete all;
      - name: Deploy to Ubuntu
        run: yarn build; yarn copy; yarn deploy
        env:
          DO_NOT_USE_ENV_FILE: true
          PORT: 3000
          DB_HOST: ${{ secrets.databaseHost }}
          DB_NAME: ${{ secrets.databaseName }}
          DB_USER_ID: ${{ secrets.databaseAuthID }}
          DB_USER_PW: ${{ secrets.databaseAuthPW }}
          JWT_TOKEN_SECRETKEY: ${{ secrets.jwtTokenSecret }}
          LOGIN_BASIC_AUTH_KEY: ${{ secrets.loginAuthKey }}
