# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Project Before Merge

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependency
        run: yarn install; npm install pm2 -g; pm2 update
      - name: Clear Running Process
        run: echo "console.log('hello')" >> temp.js; pm2 start temp.js; pm2 delete all;
      - name: Deploy to Ubuntu
        run: yarn build; yarn copy; yarn deploy
        env:
          env:
            DO_NOT_USE_ENV_FILE: true
            HTTPS: true
            HTTPS_PRIVKEY: ${{ secrets.pathPrivkey }}
            HTTPS_CHAIN: ${{ secrets.pathChain }}
            HTTPS_CERT: ${{ secrets.pathCert }}
            DB_HOST: ${{ secrets.databaseHost }}
            DB_NAME: ${{ secrets.databaseName }}
            DB_USER_ID: ${{ secrets.databaseAuthID }}
            DB_USER_PW: ${{ secrets.databaseAuthPW }}
            LOGIN_BASIC_AUTH_KEY: ${{ secrets.loginAuthKey }}
